### ISSUE TITLE
Exception in Jedis

### ISSUE THREAD

**Issue by JinuSanthRose** [nrk/predis#294]
I am getting the following exceptions while accessing Jedis sometimes.
Exception 1:
        java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:204)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:193)
	at redis.clients.jedis.Jedis.get(Jedis.java:89)
Exception 2:
 redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: invalid bulk length
	at redis.clients.jedis.Protocol.processError(Protocol.java:113)
	at redis.clients.jedis.Protocol.process(Protocol.java:131)
	at redis.clients.jedis.Protocol.read(Protocol.java:200)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:285)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:204)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:193)
	at redis.clients.jedis.Jedis.get(Jedis.java:89)
Can anyone help me to resolve this?

**Comment by nrk** [comment]
This has nothing to do with Predis, please post your issues on the [appropriate issue tracker](https://github.com/xetorthio/jedis/issues)
