### ISSUE TITLE
Command 'CLIENTSETNAME' is not a registered Redis command

### ISSUE THREAD

**Issue by Xmaksss** [nrk/predis#481]
Hello!
Can you help me?
I have [yii2-queue](https://github.com/yiisoft/yii2-queue) extension and when I run it with predis I get an error ``Exception 'Predis\ClientException' with message 'Command 'CLIENTSETNAME' is not a registered Redis command.``
```bash
Exception 'Predis\ClientException' with message 'Command 'CLIENTSETNAME' is not a registered Redis command.'

in /home/superuser/www/engine/vendor/predis/predis/src/Profile/RedisProfile.php:88

Stack trace:
#0 /home/superuser/www/engine/vendor/predis/predis/src/Client.php(323): Predis\Profile\RedisProfile->createCommand('CLIENTSETNAME', Array)
#1 /home/superuser/www/engine/vendor/predis/predis/src/Client.php(314): Predis\Client->createCommand('clientSetname', Array)
#2 [internal function]: Predis\Client->__call('clientSetname', Array)
#3 /home/superuser/www/engine/backend/components/RedisConnection.php(54): call_user_func_array(Array, Array)
#4 /home/superuser/www/engine/vendor/yiisoft/yii2-queue/src/drivers/redis/Queue.php(164): backend\components\RedisConnection->__call('clientSetname', Array)
#5 /home/superuser/www/engine/vendor/yiisoft/yii2-queue/src/drivers/redis/Queue.php(52): yii\queue\redis\Queue->openWorker()
#6 /home/superuser/www/engine/vendor/yiisoft/yii2-queue/src/drivers/redis/Command.php(45): yii\queue\redis\Queue->run()
```
What is wrong with ``$this->redis->clientSetname("$this->channel.worker.$id");``? Predis don't  have a commant ``clientSetname``, do it?

**Comment by nrk** [comment]
The command is actually `CLIENT` while `SETNAME` is a modifier, so the proper call is `$redis->client('SETNAME', $id);`.
